apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bzpwl0x7i-python 
  janus-idp.io/tekton: bzpwl0x7i-python
  backstage.io/kubernetes-id: bzpwl0x7i-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bzpwl0x7i-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml